# This is a basic workflow to help you get started with Actions

name: aws3_1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

    paths: ['input.json']
      #-'.github/workflows/**'
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "main" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
  execute_calc:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.6

      - name: Python output.py
        run: |
            ls
            cd Python/aws3
            python output.py
  
      - name: error sentence
        if: failure()
        run: |
              echo "error : incorrect input"

  load_artifacts:
    runs-on: self-hosted
    needs: execute_calc
    steps: 
      - name: Load artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./Python/aws3/output.json