# This is a basic workflow to help you get started with Actions

name: aws2_new

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: ["main"]
    inputs:
      num1:
        type: int
        required: true
        description: 'num1 data'
      
      num2:
        type: int
        required: true
        description: 'num2 data'
      
      operator:
        type: choice
        required: true
        description: 'operator'
        options:
          - "plus"
          - "minus"
          - "cross"
          - "devision"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

  write_input-data:
    
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    needs: build
    steps:
      - name: input data
        run: echo Data1:${{ github.event.inputs.num1}},  
                  Data2:${{ github.event.inputs.num2}},
                  type:${{ github.event.inputs.operator}}

  execute_calc:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    needs: write_input-data
    steps:
      - name: Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      #- name: Python_Input
        #run: python input.py ${{ github.event.inputs.num1}} ${{ github.event.inputs.num2}} ${{ github.event.inputs.operator}}
      

      - name: Python_clac.py
        run: 
              python Python/calc.py -f ${{ github.event.inputs.num1}} -s ${{ github.event.inputs.num2}} -t ${{ github.event.inputs.operator}}
      
      - name: Python_calc-help
        run: python Python/calc.py -h
        
      - name: error sentence
        if: failure()
        run: |
              echo "error : incorrect input"
      
     